<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

	
	
	<xacro:include filename="inertial_macros.xacro" />
	
	

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
    
    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>
    
    
    
    <!-- Chassis -->


    <xacro:property name="chassis_length" value="0.2"/>
    <xacro:property name="chassis_width" value="0.1"/>
    <xacro:property name="chassis_thickness" value="0.01"/>
    <xacro:property name="front_base_length" value="0.05"/>
    <xacro:property name="back_base_length" value="0.05"/>
    <xacro:property name="a" value="0.02"/>


	
	
	
	
	<!-- Create fixed world frame -->
	
	<link name="world"></link>
	
	<joint name="world_joint" type="floating">
		<parent link="world"></parent>
		<child link="chassis"></child>
		<origin xyz="0 0 0.1"></origin>
	</joint>
	
	
	
	
	
	
    <link name="chassis">
		<visual>
            <geometry>
                <box size="${chassis_length} ${chassis_thickness} ${chassis_thickness}"/>
            </geometry>
            <material name="orange"/>
            <origin xyz="0 ${-chassis_width/2 +chassis_thickness/2} 0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_thickness} ${chassis_thickness}"/>
            </geometry>
            <origin xyz="0 ${chassis_width/2 -chassis_thickness/2} 0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${chassis_thickness} ${chassis_width} ${chassis_thickness}"/>
            </geometry>
            <material name="grey"/>
            <origin xyz="${-chassis_length/2} 0 0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${chassis_thickness} ${chassis_width} ${chassis_thickness}"/>
            </geometry>
            <material name="grey"/>
            <origin xyz="${chassis_length/2} 0 0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${chassis_thickness} ${chassis_width} ${chassis_thickness}"/>
            </geometry>
            <origin xyz="${front_base_length} 0 ${chassis_thickness}"/>
        </visual>
        <visual>
            <geometry>
                <box size="${chassis_thickness} ${chassis_width} ${chassis_thickness}"/>
            </geometry>
            <origin xyz="${-back_base_length} 0 ${chassis_thickness}"/>
        </visual>
        <inertial>
			<mass value="1"/>
			<inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3"/>
		</inertial>
    </link>
    
    <gazebo reference="chassis">
		<material>Gazebo/White</material>
    </gazebo>



    




    


    <xacro:property name="l1" value="0.04"/>
    <xacro:property name="l2" value="0.01"/>
    <xacro:property name="l3" value="0.025"/>
    <xacro:property name="thickness" value="0.01"/>
    <xacro:property name="motor_side" value="0.02"/>


    <!-- Left_wheel_base-->

    <link name="left_wheel_base">
        <visual>
            <geometry>
                <box size="${l1} ${thickness} ${thickness}" />
            </geometry>
            <origin xyz="${-l1/2} 0 0"/>
            <material name="white"/>
        </visual>
        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.15">
			<origin xyz="0 ${-chassis_width/2 +chassis_thickness/2} 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <geometry>
                <box size="${thickness} ${l2} ${thickness}"/>
            </geometry>
            <origin xyz="${-l1+thickness/2} ${-l2/2-thickness/2} 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${l3} ${thickness} ${thickness}"/>
            </geometry>
            <origin xyz="${-l1-l3/2} ${-l2} 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${motor_side} ${motor_side} ${motor_side}"/>
            </geometry>
            <origin xyz="${-l1-l3-motor_side/2} ${-l2} 0.0" rpy="0.0 0.0 0.0"/>
            
        </visual>
        <inertial>
			<mass value="1"/>
			<inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3"/>
		</inertial>
    </link>
    
    <gazebo reference="left_wheel_base_joint">
		<material>Gazebo/Blue</material>
    </gazebo>

    <joint name="left_wheel_base_joint" type="continuous">
        <parent link="chassis"/>
        <child link="left_wheel_base"/>
        <origin xyz="${front_base_length} ${chassis_width/2-a} ${chassis_thickness/2}" rpy="0.0 ${-pi/2} 0.0"/>
        
    </joint>

    

    <!-- Left_wheel-->

    <xacro:property name="wheel_radius" value="0.025"/>
    <xacro:property name="wheel_length" value="0.01"/>

    <link name="left_wheel">
        <visual>
            <geometry>
                <box size="${thickness} ${l2-wheel_length/2-motor_side/2} ${thickness}"/>
            </geometry>
            <origin xyz="0 ${-(l2-wheel_length/2-motor_side/2+wheel_length)/2} 0"/>
			<material name="grey"/>      

        </visual>
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0.0" rpy="${pi/2} 0.0 0.0"/> 
			<material name="grey"/>      
        </visual>                    
    </link>
    

    <joint name="left_wheel_joint" type="continuous">
        <parent link="left_wheel_base"/>
        <child link="left_wheel"/>
        <origin xyz="${-l1-l3-motor_side/2} ${0} 0"/>
        <axis xyz="0 1 0"/>
        
    </joint>




    <!-- right_wheel_base-->

    <link name="right_wheel_base">
        <visual>
            <geometry>
                <box size="${l1} ${thickness} ${thickness}" />
            </geometry>
            <origin xyz="${-l1/2} 0 0"/>
            <material name="white"/>
        </visual>
        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.15">
			<origin xyz="0 ${-chassis_width/2 +chassis_thickness/2} 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <geometry>
                <box size="${thickness} ${l2} ${thickness}"/>
            </geometry>
            <origin xyz="${-l1+thickness/2} ${-l2/2-thickness/2} 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${l3} ${thickness} ${thickness}"/>
            </geometry>
            <origin xyz="${-l1-l3/2} ${-l2} 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${motor_side} ${motor_side} ${motor_side}"/>
            </geometry>
            <origin xyz="${-l1-l3-motor_side/2} ${-l2} 0.0" rpy="0.0 0.0 0.0"/>
            
        </visual>
        <inertial>
			<mass value="1"/>
			<inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3"/>
		</inertial>
    </link>
    
    <gazebo reference="right_wheel_base_joint">
		<material>Gazebo/Blue</material>
    </gazebo>

    <joint name="right_wheel_base_joint" type="continuous">
        <parent link="chassis"/>
        <child link="right_wheel_base"/>
        <origin xyz="${front_base_length} ${-chassis_width/2+a} ${chassis_thickness/2}" rpy="0.0 ${-pi/2} ${pi}"/>
        
    </joint>


    <!-- right_wheel-->


    <link name="right_wheel">
        <visual>
            <geometry>
                <box size="${thickness} ${l2-wheel_length/2-motor_side/2} ${thickness}"/>
            </geometry>
            <origin xyz="0 ${-(l2-wheel_length/2-motor_side/2+wheel_length)/2} 0"/>
            <material name="grey"/>
        </visual>
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0.0" rpy="${pi/2} 0.0 0.0"/> 
            <material name="grey"/>      
        </visual>
        <inertial>
			<mass value="1"/>
			<inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3"/>
		</inertial>

    </link>
    
    <gazebo reference="right_wheel">
		<material>Gazebo/Black</material>
    </gazebo>


    <joint name="right_wheel_joint" type="continuous">
        <parent link="right_wheel_base"/>
        <child link="right_wheel"/>
        <origin xyz="${-l1-l3-motor_side/2} ${0} 0"/>
        <axis xyz="0 1 0"/>
        
    </joint>
    
    <!-- castor wheel-->
    
    <link name="castor_wheel">
		<visual>
			<geometry>
				<box size="${thickness} ${thickness} ${l1+l3}"/>
			</geometry>
			<material name="white"/>
		</visual>
		<visual>
			<geometry>
				<sphere radius="${wheel_radius}"/>
			</geometry>
			<origin xyz="0 0 ${-(l1+l3)/2-wheel_radius+motor_side/4}"/>
		</visual>
    </link>
	
	
	<joint name="castor_joint" type="fixed">
		<parent link="chassis"></parent>
		<child link="castor_wheel"></child>
        <origin xyz="${-front_base_length} 0 ${-2*chassis_thickness}" />
	</joint>


   
	    

    





</robot>