motor_state:
  ros__parameters:
    frequency: 20

gui:
  ros__parameters:
    frequency: 20

real_world:
  ros__parameters:
    frequency: 20

sim:
  ros__parameters:
    frequency: 20

slider_publisher:
  ros__parameters:
    frequency: 20
